# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks! # config for Chart

target 'JobITTrending' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # pod 'Firebase/Auth'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'

  # config for Chart <<<
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
  'Core',
  'ART',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTLinkingIOS',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'DevSupport',
  'CxxBridge',
  ]
    
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
  pod 'RNCharts', :path => '../src/components/ChartWrapper/RNCharts.podspec'
  pod 'SwiftyJSON', '4.0.0'
  pod 'Charts', '3.1.1'
  # >>>
end

# config for Chart <<<
swift4 = ['Charts']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if swift4.include?(target.name)
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end
#>>>
