# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JobITTrending' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # pod 'Firebase/Auth'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  #dummy
  # pod 'SwiftyJSON', '4.2.0'      
  # pod 'Charts', '3.2.1' 
end
swift4 = ['Charts']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if swift4.include?(target.name)
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end