# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JobITTrending' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # pod 'Firebase/Auth'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
end
